name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml, ctype, json, tokenizer

    - name: Install Composer Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear

    - name: Deploy to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        port: ${{ secrets.HOSTINGER_PORT }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "."
        target: "${{ secrets.DEPLOY_PATH }}"
        strip_components: 1
